spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  zipkin:
    baseUrl: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1
    web:
      skipPattern: (^cleanup.*|.+favicon.*)
management:
  endpoints:
    web:
      exposure:
        include: prometheus
    enabled-by-default: true

